project:
  type: website
  preview:
    port: 3000
    browser: true
    watch-inputs: true
    navigate: true
  output-dir: docs

website:
  title: 'Luxorum Dashboard Docs'
  sidebar:
    style: "floating"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Documentation"
        contents:
          - text: "Getting Started"
            href: getting-started.qmd
          - text: "Features"
            href: features.qmd
          - text: "Deployment"
            href: deployment.qmd
          - text: "API Reference"
            href: api-reference.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
